add_newline = true
line_break.disabled = true

right_format = """$time"""

[time]
disabled = true
format = '[$time](#4C566A)'
time_format = "%T"

[directory]
format = "[$read_only](red)[ïŸ ](blue)[$path](bold italic #4c566a) "
read_only = "ïŸ "
fish_style_pwd_dir_length = 1
truncation_length = 4

[character]
error_symbol = "[ï” ](red)"
success_symbol = "[ï” ](green)"
vicmd_symbol = "[ï” ](yellow)"

[package]
symbol = "ï£– "
style = "bold #D08770"

[c] 
symbol = "î˜ "
style = "bold cyan"
detect_extensions = ["c", "h", "cpp"]
commands = [ [ "g++", "--version" ], [ "gcc", "--version" ], [ "clang", "--version" ] ]

[nodejs]
format = "via [ïŸ— $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[python]
symbol = "î˜† "
format = 'via [${symbol}(${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_version_name = true
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
version_format = "v${raw}"

[lua]
format = "via [î˜  $version](bold blue) "

[git_branch]
symbol = "ï˜ "
format = "on [$symbol$branch]($style) "
style = "bold #B48EAD"

[cmake]
format = "with [ï¨µ$version](bold #B48EAD) "
detect_files = ["CMakeLists.txt", "CMakeCache.txt"]

[java]
format = "via [ğŸŒŸ $version](bold yellow) "

[golang]
symbol = "ï³‘ "

[custom.docker]
files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"
symbol = "ïŒˆ "
format = "with [$symbol]($style) "

[git_status]
style = "bold red"
ahead = '[ ï‚ª $count](bold green)'
behind = '[ ï‚« $count](bold green)'
untracked = '[ ï™ $count](bold yellow)'
modified = '[ ï…‹ $count](bold #D08770)'
staged = '[ ïƒ¾ $count](bold green)'
renamed = '[ ï…† $count](bold yellow)'
deleted = '[ï— $count](bold red)'
conflicted = '[ï®— $count](bold cyan)'
diverged = '[â†• ${ahead_count}â‡£${behind_count}](bold cyan)'
stashed = '[ï°© $count](bold yellow)'
