"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character] # The name of the module we are configuring is 'character'
success_symbol = "[ â¯](bold green)"
error_symbol = "[ â¯](bold red)"
vimcmd_symbol = "[ â¯](bold green)"
vimcmd_visual_symbol = "[ â¯](bold yellow)"
vimcmd_replace_symbol = "[ â¯](bold purple)"
vimcmd_replace_one_symbol = "[ â¯](bold purple)"

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = "bold blue"

[package]
symbol = "ó°“ "
style = 'bold yellow'

[nodejs]
symbol = "ó°‹˜ "

[python]
symbol = "îœ¼ "

[lua]
symbol = "î˜  "

[git_branch]
symbol = "î©¨ "
format = "on [$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "bold red dimmed"
ahead = '[ ï‚ª $count](bold green)'
behind = '[ ï‚« $count](bold green)'
untracked = '[ ï™ $count](bold yellow)'
modified = '[ ï…‹ $count](bold orange)'
staged = '[ ïƒ¾ $count](bold green)'
renamed = '[ ï…† $count](bold yellow)'
deleted = '[ï— $count](bold red)'
conflicted = '[ï®— $count](bold cyan)'
diverged = '[â†• ${ahead_count}â‡£${behind_count}](bold cyan)'
stashed = '[ï°© $count](bold yellow)'

[cmake]
symbol = "ó°²‰ "

[golang]
symbol = "î˜§ "

[rust]
symbol = "î¨ "

[c]
symbol = "î˜ "

[docker_context]
format = 'has [ïŒˆ docker ](cyan bold)'

[bun]
symbol = "ğŸ™ "

[dotnet]
format = "via [$symbol($version )]($style)"
symbol = "ó°ª® "
style = "bold purple"

[ruby]
symbol = 'î˜„ '
disabled = true

[java]
symbol = "î‰– "
format = 'use [${symbol}(${version} )]($style)'
style = "bold red dimmed"

[gradle]
symbol = "î™  "

[kotlin]
symbol = "î˜´ "
